### PR TITLE
Update dependencies. Replace jshint/jscs with eslint.

### PR DESCRIPTION
**Pull request by ariutta**
Hi @bumbu,

I'm opening a new pull request to address the comments you had on [the previous one](https://github.com/ariutta/svg-pan-zoom/pull/344). This way, the commit history will be cleaner.

We should also publish a point release to NPM so that `npm install` doesn't complain about outdated dependencies, but I didn't bump this version.

### CODE REVIEW

**Comment by ariutta** [comment]
I don't know that anyone is using the `bower.json` file, so I removed it. We can also then remove the dev dependency `gulp-config-sync`.

**Comment by ariutta** [comment]
I moved the autoformatter changes out of this pull request, but I'd still like to use an autoformatter. Here are two branches with different options:
* [Prettier](https://github.com/ariutta/svg-pan-zoom/tree/autoformatter-prettier)
* [Custom ESLint](https://github.com/ariutta/svg-pan-zoom/tree/autoformatter-custom)

I've been using [Prettier](https://prettier.io/docs/en/why-prettier.html) on my other projects. The custom ESLint option is configured to generally match the current style. I'm OK with whatever you prefer.

**Comment by bumbu** [comment]
@ariutta this PR looks good to me. As for formatter - I also prefer Prettier as it completely removes the worry of formatting the code :)

**Comment by ariutta** [comment]
@bumbu I went ahead and merged this pull request. I also switched us over to using the default formatting from Prettier. Thanks for the review!

**Comment by bumbu** [comment]
@ariutta thanks for taking care of this!

**Pull request merged**
