### PR TITLE
add possibility to bind events on custom elements instead of the whole svg

### PR DESCRIPTION
**Pull request by VeNoMiS**
Added eventBindSelector

### CODE REVIEW

**Comment by ariutta** [comment]
Hi @VeNoMiS,

Thanks for the pull request! @bumbu is currently most active in managing this project, so his preference is most important in choosing how to merge this. I just had a few comments.

1. @bumbu prefers to rely on automatic semicolon insertion, so let's stick with his preference here.
2. We want to limit the core of this project to a reasonable in size, so in issue #98, @bumbu and I have been thinking about how we could restructure it to allow for plugins while keeping the core small. Do you have thoughts on a plugin model, and could this pull request be a plugin?
3. Why can't code add a single event listener to the parent element and then filter the event stream by `event.target' instead of adding multiple event listeners directly to the targets, which can hurt performance?

**Comment by bumbu** [comment]
Hi @VeNoMiS,

Thanks for the pull request. I saw your messages on stackoverflow and this pull request makes sense. But I have just one comment: please remove semicolons that you added in this pull request. It just makes the pull request messy, so it is hard to understand what actually was added/edited.

@ariutta - I agree with you that it would look better as a plugin, but it seems that it will require quite a lot of refactor as from what I know main problem that is solved by this pull request is that plugin prevents events bubbling. This pull request solves the problem partially by listening and preventing events only from specific elements. 
And about performance - it should make no difference as here only one selector (and not multiple) is used.

**Comment by VeNoMiS** [comment]
Hi guys ( @ariutta , @bumbu ),
i've removed all the commas included into the request but the diff still look messy.
Let me know if it's ok or i need to revert all

**Comment by bumbu** [comment]
Hi @VeNoMiS,

Sorry that it took so much time. I did add this functionality to the library (but with small changes). 
I also made it work with zooming (not only pan events) and added events removal. [Here's the documentation section](https://github.com/ariutta/svg-pan-zoom#listening-for-panzoom-events-on-a-child-svg-element) about it.

Thank you for your work!

**Pull request closed without merging**
