### PR TITLE
minor tweak to add a contain function and option similar to the fit function/option

### PR DESCRIPTION
**Pull request by timmh**

### CODE REVIEW

**Comment by bumbu** [comment]
This is a really good pull request. And simple. Thank you!

**Comment by lydell** [comment]
Hi! I know it’s 5 years later, but I’m really confused – what is the difference between `fit` and `contain`? As far as I can tell they are 100% identical.

**Comment by timmh** [comment]
Hey @lydell, `fit` ensures that the whole of the SVG is visible, possibly with horizontal or vertical empty space. `contain` ensures that some part of the SVG covers the whole viewport, possibly by cropping some part of the image. The distinction is only meaningful if your viewport has a different aspect ratio than your SVG.

**Comment by lydell** [comment]
Thanks, that’s really helpful! And now I finally see the difference in the code: It’s `Math.min` vs `Math.max`…

**Comment by timmh** [comment]
Yes, a change so simple I understand it five years later for once ;)

**Pull request merged**
