### PR TITLE
Update typings

### PR DESCRIPTION
**Pull request by bumbu**
Hey @Yimiprod 
I made some updates to old typings in hope to make them more consistent. 
Also I added typings for the new option and method. 
Please check and merge if it's fine. 
I'll make a new release after that. 
Thanks!

### CODE REVIEW

**Comment by Yimiprod** [comment]
@bumbu the code look ok but it missing the version bump at line 3.
`npm test` fail for me.

**Comment by bumbu** [comment]
Hey @Yimiprod 
I'll bump the version on build. 
Did you run the build before running tests? Test uses files from `dist` folder.

**Comment by Yimiprod** [comment]
ATM i only check manually if there's no error in the file. I'm looking if there's an easier way to test it.

**Comment by Yimiprod** [comment]
Ok i found out how to check.
I can push it to your branch or you could add it: `npm i -D typescript`.
Update **tsconfig.jons** with `"noEmit": true,` in compilerOptions.
Add script in **package.json** `"test-typescript": "tsc"`.

Now `npm run test-typescript` should make a dry-run, if anything's wrong in the definition or in the test, it will fail.

**Comment by bumbu** [comment]
Hey @Yimiprod 
Thanks for the explanations. I'll merge this one and make a release. 
If you get some time to create a simple test runner - please make a separate PR. 
Thanks!

**Pull request merged**
