### PR TITLE
Add thumbnailViewer demo

### PR DESCRIPTION
**Pull request by kubohiroya**
prototype demo for issue #110

### CODE REVIEW

**Comment by calanor** [comment]
Very good!
but for large and complex svg its a best option use a snapshot instead de same svg.

**Comment by kubohiroya** [comment]
image

**Comment by bumbu** [comment]
@kubohiroya - Thank you!

**Comment by timelyportfolio** [comment]
this is great, thanks guys!

**Comment by navinSing** [comment]
can we have something like 
drag to draw rect on thumbnal; to zoom into that part of original svg.

**Comment by navinSing** [comment]
also can we create a dynamic svg/image of the generated svg
rater than a fixed one like tiger.svg

**Comment by ariutta** [comment]
Hi @navinSing, could you explain further about dynamic vs. fixed? I'm not sure that I understand.

**Comment by navinSing** [comment]
i am changing some part of svg with js.

Regards,
Shravan

**Comment by bumbu** [comment]
@navinSing it is totaly possible to have _drag to draw_ on thumbnail for zoom.
I'm not sure what you mean by `also can we create a dynamic svg/image of the generated svg` but this also seems to be possible. 

But you'll have to create them by yourself. In case that you do - you're welcome to share your solution and we'll merge it into codebase.

**Comment by nanfb** [comment]
For large svg graphics, rendering twice in this way will cause very serious performance problems. Is it possible to use pictures instead

**Pull request merged**
